language: cpp
compiler:
  - gcc
  - clang
env:
  global:
    - secure: "a7S8evtkUggaV64MyXoFO5yfnFxjViGd8PcZwJQtTPHV6zIpVkcoz2z1NDMHBp63mblwno5C6Qr2IYoRX3gNr2Tj5uMX/oJmvnek3vChXlRps0BcuRVE9JFK4nxeLOmF2eEKC9/m0Qk6lcjB77cuS1GYqIuFbGF49NEEBGjq/2I="
    - APT_DEPENDENCIES="doxygen doxygen-latex libboost-all-dev libeigen3-dev liblapack-dev libblas-dev gfortran"
    - GIT_DEPENDENCIES="jrl-umi3218/jrl-mathtools jrl-umi3218/jrl-mal laas/abstract-robot-dynamics"
    - LCOV_IGNORE_RULES="*unitTesting*"
notifications:
  email: hpp-source@laas.fr
branches: 
  only:
  - master
  - debian
script: ./.travis/run build
after_success:  ./.travis/run after_success
after_failure:  ./.travis/run after_failure
before_install: ./.travis/run before_install
matrix:
  allow_failures:
    - compiler: clang
