jrlDelegate::humanoidDynamicRobot Class Reference
jrlDelegate::humanoidDynamicRobot Class Reference
User Classes
Template to implement a non abstract class describing a humanoid robot with dynamics.
#include <jrl/dynamics/humanoiddynamicrobot.hh>
Public Member Functions
humanoidDynamicRobot (CjrlRobotDynamicsObjectFactory *inObjectFactory)
humanoidDynamicRobot (humanoidDynamicRobot *inHDRNA)
humanoidDynamicRobot ()
virtual ~humanoidDynamicRobot ()
Destructor.
Joints specific to humanoid robots
virtual void waist (CjrlJoint *inWaist)
Set the pointer to the waist.
virtual CjrlJoint * waist () const
Get a pointer to the waist.
virtual void chest (CjrlJoint *inChest)
Set the pointer to the chest.
virtual CjrlJoint * chest () const
Get a pointer to the chest.
virtual void leftWrist (CjrlJoint *inLeftWrist)
Set the pointer to the left wrist joint.
virtual CjrlJoint * leftWrist () const
Get a pointer to the left wrist.
virtual void rightWrist (CjrlJoint *inRightWrist)
Set the pointer to the right wrist joint.
virtual CjrlJoint * rightWrist () const
Get a pointer to the right wrist.
virtual void rightHand (CjrlHand *inRightHand)
Set the pointer to the right hand.
virtual CjrlHand * rightHand () const
Get a pointer to the right hand.
virtual void leftHand (CjrlHand *inLeftHand)
Set the pointer to the left hand.
virtual CjrlHand * leftHand () const
Get a pointer to the left hand.
virtual double getHandClench (CjrlHand *inHand)
Get the hand clench value.
virtual bool setHandClench (CjrlHand *inHand, double inClenchingValue)
Set the hand clench value.
virtual void leftAnkle (CjrlJoint *inLeftAnkle)
Set the pointer to the left ankle joint.
virtual CjrlJoint * leftAnkle () const
Get a pointer to the left ankle.
virtual void rightAnkle (CjrlJoint *inRightAnkle)
Set the pointer to the right ankle joint.
virtual CjrlJoint * rightAnkle () const
Get a pointer to the right ankle.
virtual void leftFoot (CjrlFoot *inLeftFoot)
Set the pointer to the left foot joint.
virtual CjrlFoot * leftFoot () const
Get a pointer to the left foot.
virtual void rightFoot (CjrlFoot *inRightFoot)
Set the pointer to the right foot joint.
virtual CjrlFoot * rightFoot () const
Get a pointer to the right foot.
virtual void gazeJoint (CjrlJoint *inGazeJoint)
Set gaze joint.
virtual CjrlJoint * gazeJoint () const
Get gaze joint.
virtual void gaze (const vector3d &inDirection, const vector3d &inOrigin)
Set the gaze orientation and position in the local frame of the gaze joint.
virtual const vector3d & gazeOrigin () const
Get a point on the gaze straight line.
virtual const vector3d & gazeDirection () const
Get the direction of gaze.
Zero momentum point
@}
virtual const vector3d & zeroMomentumPoint () const
return the coordinates of the Zero Momentum Point.
int dynamicsJRLJapan::parseOpenHRPVRMLFile (CjrlHumanoidDynamicRobot &ajrlHumanoidDynamicRobot, std::string &OpenHRPVRMLFile, std::string &MapJointToRankFileName, std::string &SpecificitiesFileName, std::vector< BodyGeometricalData > &VectorOfURLs, bool ReadGeometryInformation)
Detailed Description
Template to implement a non abstract class describing a humanoid robot with dynamics.
This template takes a class implementing the methods of the template CjrlRobotDynamicsObjectConstructor.
Constructor & Destructor Documentation
jrlDelegate::humanoidDynamicRobot::humanoidDynamicRobot (CjrlRobotDynamicsObjectFactory * inObjectFactory) [inline]
References jrlDelegate::dynamicRobot::setDynamicRobot().
jrlDelegate::humanoidDynamicRobot::humanoidDynamicRobot (humanoidDynamicRobot * inHDRNA) [inline]
References jrlDelegate::dynamicRobot::setDynamicRobot().
jrlDelegate::humanoidDynamicRobot::humanoidDynamicRobot () [inline]
References jrlDelegate::dynamicRobot::setDynamicRobot().
virtual jrlDelegate::humanoidDynamicRobot::~humanoidDynamicRobot () [inline, virtual]
Destructor.
Member Function Documentation
virtual void jrlDelegate::humanoidDynamicRobot::chest (CjrlJoint * inChest) [inline, virtual]
Set the pointer to the chest.
Note:
for some humanoid robots, the waist and the chest are the same joints.
Implements CjrlHumanoidDynamicRobot.
References CjrlHumanoidDynamicRobot::chest().
virtual CjrlJoint* jrlDelegate::humanoidDynamicRobot::chest () const [inline, virtual]
Get a pointer to the chest.
Note:
for some humanoid robots, the waist and the chest are the same joints.
Implements CjrlHumanoidDynamicRobot.
References CjrlHumanoidDynamicRobot::chest().
virtual void jrlDelegate::humanoidDynamicRobot::gaze (const vector3d & inDirection, const vector3d & inOrigin) [inline, virtual]
Set the gaze orientation and position in the local frame of the gaze joint.
Returns:
inOrigin a point on the gaze straight line,
inDirection the direction of the gaze joint.
Implements CjrlHumanoidDynamicRobot.
References CjrlHumanoidDynamicRobot::gaze().
virtual const vector3d& jrlDelegate::humanoidDynamicRobot::gazeDirection () const [inline, virtual]
Get the direction of gaze.
Implements CjrlHumanoidDynamicRobot.
References CjrlHumanoidDynamicRobot::gazeDirection().
virtual void jrlDelegate::humanoidDynamicRobot::gazeJoint (CjrlJoint * inGazeJoint) [inline, virtual]
Set gaze joint.
Note:
For most humanoid robots, the gaze joint is the head.
Implements CjrlHumanoidDynamicRobot.
References CjrlHumanoidDynamicRobot::gazeJoint().
virtual CjrlJoint* jrlDelegate::humanoidDynamicRobot::gazeJoint () const [inline, virtual]
Get gaze joint.
Implements CjrlHumanoidDynamicRobot.
References CjrlHumanoidDynamicRobot::gazeJoint().
virtual const vector3d& jrlDelegate::humanoidDynamicRobot::gazeOrigin () const [inline, virtual]
Get a point on the gaze straight line.
Implements CjrlHumanoidDynamicRobot.
References CjrlHumanoidDynamicRobot::gazeOrigin().
virtual double jrlDelegate::humanoidDynamicRobot::getHandClench (CjrlHand * inHand) [inline, virtual]
Get the hand clench value.
This is a scalar value ranging between 0 and 1 which describes the hand clench (0 for open and 1 for closed hand)
Implements CjrlHumanoidDynamicRobot.
References CjrlHumanoidDynamicRobot::getHandClench().
virtual void jrlDelegate::humanoidDynamicRobot::leftAnkle (CjrlJoint * inLeftAnkle) [inline, virtual]
Set the pointer to the left ankle joint.
Implements CjrlHumanoidDynamicRobot.
References CjrlHumanoidDynamicRobot::leftAnkle().
virtual CjrlJoint* jrlDelegate::humanoidDynamicRobot::leftAnkle () const [inline, virtual]
Get a pointer to the left ankle.
Implements CjrlHumanoidDynamicRobot.
References CjrlHumanoidDynamicRobot::leftAnkle().
virtual void jrlDelegate::humanoidDynamicRobot::leftFoot (CjrlFoot * inLeftFoot) [inline, virtual]
Set the pointer to the left foot joint.
Implements CjrlHumanoidDynamicRobot.
References CjrlHumanoidDynamicRobot::leftFoot().
virtual CjrlFoot* jrlDelegate::humanoidDynamicRobot::leftFoot () const [inline, virtual]
Get a pointer to the left foot.
Implements CjrlHumanoidDynamicRobot.
References CjrlHumanoidDynamicRobot::leftFoot().
virtual void jrlDelegate::humanoidDynamicRobot::leftHand (CjrlHand * inLeftHand) [inline, virtual]
Set the pointer to the left hand.
Implements CjrlHumanoidDynamicRobot.
References CjrlHumanoidDynamicRobot::leftHand().
virtual CjrlHand* jrlDelegate::humanoidDynamicRobot::leftHand () const [inline, virtual]
Get a pointer to the left hand.
Implements CjrlHumanoidDynamicRobot.
References CjrlHumanoidDynamicRobot::leftHand().
virtual void jrlDelegate::humanoidDynamicRobot::leftWrist (CjrlJoint * inLeftWrist) [inline, virtual]
Set the pointer to the left wrist joint.
Implements CjrlHumanoidDynamicRobot.
References CjrlHumanoidDynamicRobot::leftWrist().
virtual CjrlJoint* jrlDelegate::humanoidDynamicRobot::leftWrist () const [inline, virtual]
Get a pointer to the left wrist.
Implements CjrlHumanoidDynamicRobot.
References CjrlHumanoidDynamicRobot::leftWrist().
virtual void jrlDelegate::humanoidDynamicRobot::rightAnkle (CjrlJoint * inRightAnkle) [inline, virtual]
Set the pointer to the right ankle joint.
Implements CjrlHumanoidDynamicRobot.
References CjrlHumanoidDynamicRobot::rightAnkle().
virtual CjrlJoint* jrlDelegate::humanoidDynamicRobot::rightAnkle () const [inline, virtual]
Get a pointer to the right ankle.
Implements CjrlHumanoidDynamicRobot.
References CjrlHumanoidDynamicRobot::rightAnkle().
virtual void jrlDelegate::humanoidDynamicRobot::rightFoot (CjrlFoot * inRightFoot) [inline, virtual]
Set the pointer to the right foot joint.
Implements CjrlHumanoidDynamicRobot.
References CjrlHumanoidDynamicRobot::rightFoot().
virtual CjrlFoot* jrlDelegate::humanoidDynamicRobot::rightFoot () const [inline, virtual]
Get a pointer to the right foot.
Implements CjrlHumanoidDynamicRobot.
References CjrlHumanoidDynamicRobot::rightFoot().
virtual void jrlDelegate::humanoidDynamicRobot::rightHand (CjrlHand * inRightHand) [inline, virtual]
Set the pointer to the right hand.
Implements CjrlHumanoidDynamicRobot.
References CjrlHumanoidDynamicRobot::rightHand().
virtual CjrlHand* jrlDelegate::humanoidDynamicRobot::rightHand () const [inline, virtual]
Get a pointer to the right hand.
Implements CjrlHumanoidDynamicRobot.
References CjrlHumanoidDynamicRobot::rightHand().
virtual void jrlDelegate::humanoidDynamicRobot::rightWrist (CjrlJoint * inRightWrist) [inline, virtual]
Set the pointer to the right wrist joint.
Implements CjrlHumanoidDynamicRobot.
References CjrlHumanoidDynamicRobot::rightWrist().
virtual CjrlJoint* jrlDelegate::humanoidDynamicRobot::rightWrist () const [inline, virtual]
Get a pointer to the right wrist.
Implements CjrlHumanoidDynamicRobot.
References CjrlHumanoidDynamicRobot::rightWrist().
virtual bool jrlDelegate::humanoidDynamicRobot::setHandClench (CjrlHand * inHand, double inClenchingValue) [inline, virtual]
Set the hand clench value.
This is a scalar value ranging between 0 and 1 which describes the hand clench (0 for open and 1 for closed hand)
Returns:
false if parameter 2 is out of range
Implements CjrlHumanoidDynamicRobot.
References CjrlHumanoidDynamicRobot::setHandClench().
virtual void jrlDelegate::humanoidDynamicRobot::waist (CjrlJoint * inWaist) [inline, virtual]
Set the pointer to the waist.
Implements CjrlHumanoidDynamicRobot.
References CjrlHumanoidDynamicRobot::waist().
virtual CjrlJoint* jrlDelegate::humanoidDynamicRobot::waist () const [inline, virtual]
Get a pointer to the waist.
Implements CjrlHumanoidDynamicRobot.
References CjrlHumanoidDynamicRobot::waist().
virtual const vector3d& jrlDelegate::humanoidDynamicRobot::zeroMomentumPoint () const [inline, virtual]
return the coordinates of the Zero Momentum Point.
Implements CjrlHumanoidDynamicRobot.
References CjrlHumanoidDynamicRobot::zeroMomentumPoint().
Friends And Related Function Documentation
int dynamicsJRLJapan::parseOpenHRPVRMLFile (CjrlHumanoidDynamicRobot & ajrlHumanoidDynamicRobot, std::string & OpenHRPVRMLFile, std::string & MapJointToRankFileName, std::string & SpecificitiesFileName, std::vector< BodyGeometricalData > & VectorOfURLs, bool ReadGeometryInformation) [friend]