Document: jrl-dynamic
Title: Debian jrl-dynamic Manual
Author: <insert document author here>
Abstract: This manual describes what jrl-dynamic is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/jrl-dynamic/jrl-dynamic.sgml.gz

Format: postscript
Files: /usr/share/doc/jrl-dynamic/jrl-dynamic.ps.gz

Format: text
Files: /usr/share/doc/jrl-dynamic/jrl-dynamic.text.gz

Format: HTML
Index: /usr/share/doc/jrl-dynamic/html/index.html
Files: /usr/share/doc/jrl-dynamic/html/*.html
